accounting:
  checkpoint_dir: /sharefs/qiukeyue/project/logs/qiukeyue_bfn_sbdd/train_multi_kekulize/4b71cc6_26712/checkpoints
  dump_config_path: /sharefs/qiukeyue/project/logs/qiukeyue_bfn_sbdd/train_multi_kekulize/4b71cc6_26712/config.yaml
  generated_mol_dir: /sharefs/qiukeyue/project/logs/qiukeyue_bfn_sbdd/train_multi_kekulize/4b71cc6_26712/generated_mol
  logdir: /sharefs/qiukeyue/project/logs/qiukeyue_bfn_sbdd/train_multi_kekulize/4b71cc6_26712
  test_outputs_dir: /sharefs/qiukeyue/project/logs/qiukeyue_bfn_sbdd/train_multi_kekulize/4b71cc6_26712/test_outputs
  wandb_logdir: /sharefs/qiukeyue/project/logs/qiukeyue_bfn_sbdd/train_multi_kekulize/4b71cc6_26712
best_ckpt: val_loss
ckpt_path: null
data:
  atom_decoder:
  - H
  - C
  - N
  - O
  - F
  - P
  - S
  - Cl
  colors_dic:
  - '#FFFFFF99'
  - C7
  - C0
  - C3
  - C1
  - C4
  - C8
  - C9
  name: pl
  normalizer_dict:
    pos: 2.0
  path: /sharefs/share/sbdd_data/crossdocked_v1.1_rmsd1.0_pocket10
  radius_dic:
  - 0.3
  - 0.6
  - 0.6
  - 0.6
  - 0.6
  - 0.6
  - 0.6
  - 0.6
  smiles_path: /sharefs/share/sbdd_data/crossdocked_v1.1_rmsd1.0_pocket10_smiles.pkl
  split: /sharefs/share/sbdd_data/crossdocked_pose_split_kekulize.pt
  transform:
    ligand_atom_mode: add_aromatic
  version: kekulize
  with_split: true
debug: false
decouple_mode: none
dynamics:
  beta1: 1.0
  beta1_aromatic: 3.0
  beta1_bond: 1.0
  beta1_charge: 1.5
  bond_net_type: lin
  center_pos_mode: protein
  destination_prediction: true
  discrete_steps: 1000
  ligand_atom_aromatic_dim: 2
  ligand_atom_charge_dim: 3
  ligand_atom_feature_dim: 13
  ligand_atom_type_dim: 8
  net_config:
    act_fn: relu
    adaptive_norm: false
    cutoff_mode: knn
    dropout: 0.1
    edge_feat_dim: 4
    h_node_in_bond_net: true
    hidden_dim: 128
    knn: 32
    n_heads: 16
    name: unio2net_bond
    norm: true
    num_blocks: 1
    num_bond_classes: 4
    num_layers: 4
    num_r_gaussian: 20
    r_max: 10.0
    sync_twoup: false
    x2h_out_fc: false
  node_indicator: true
  pos_init_mode: zero
  pred_connectivity: false
  pred_given_all: false
  protein_atom_feature_dim: 27
  sampling_strategy: end_back_pmf
  self_condition: true
  sigma1_coord: 0.05
  t_min: 0.0001
  time_emb_dim: 0
  time_emb_mode: simple
  use_discrete_t: true
empty_folder: false
evaluation:
  batch_size: 100
  docking_config:
    exhaustiveness: 16
    mode: vina_score
    protein_root: /sharefs/share/sbdd_data/test_set
  fix_bond: false
  ligand_path: 'null'
  num_samples: 10
  protein_path: 'null'
  sample_num_atoms: ref
  sample_steps: 100
  time_scheduler_path: 'null'
exp_name: train_multi_kekulize
logging_level: warning
no_wandb: false
project_name: qiukeyue_bfn_sbdd
revision: 4b71cc6_26712
seed: 1234
test_only: false
time_decoupled: false
timewarp:
  decay: 0.0
  num_bins: 100
  num_cat_features: 1
  num_cont_features: 1
  sigma_max_cat: 1
  sigma_max_cont: 1
  sigma_min_cat: 0
  sigma_min_cont: 0
  timewarp_type: bytype
train:
  batch_size: 4
  bond_loss_weight: 10
  ckpt_freq: 1
  ema_decay: 0.999
  epochs: 15
  log_gradient_scale_interval: 100
  max_grad_norm: Q
  num_workers: 8
  optimizer:
    beta1: 0.95
    beta2: 0.999
    lr: 0.0005
    type: adam
    weight_decay: 0
  pos_noise_std: 0
  random_rot: false
  resume: false
  scheduler:
    factor: 0.6
    max_iters: 20000
    min_lr: 1.0e-06
    patience: 10
    type: plateau
  v_loss_weight: 1
  val_freq: 1000
  val_mode: sample
visual:
  save_mols: false
  visual_chain: false
  visual_nums: 10
wandb_resume_id: null
