accounting:
  checkpoint_dir: ./logs/bfn_sbdd/demo/default/checkpoints
  dump_config_path: ./logs/bfn_sbdd/demo/default/config.yaml
  generated_mol_dir: ./logs/bfn_sbdd/demo/default/generated_mol
  logdir: ./logs/bfn_sbdd/demo/default
  test_outputs_dir: ./output
  val_outputs_dir: ./logs/bfn_sbdd/demo/default/val_outputs
  wandb_logdir: ./logs/bfn_sbdd/demo/default
data:
  atom_decoder:
  - H
  - C
  - N
  - O
  - F
  - P
  - S
  - Cl
  colors_dic:
  - '#FFFFFF99'
  - C7
  - C0
  - C3
  - C1
  - C4
  - C8
  - C9
  name: pl_tr
  normalizer_dict:
    pos: 2.0
  path: ./data/crossdocked_v1.1_rmsd1.0_pocket10
  radius_dic:
  - 0.3
  - 0.6
  - 0.6
  - 0.6
  - 0.6
  - 0.6
  - 0.6
  - 0.6
  split: ./crossdocked_pocket10_pose_split.pt
  transform:
    ligand_atom_mode: add_aromatic
  with_split: true
debug: false
dynamics:
  beta1: 1.5
  center_pos_mode: protein
  destination_prediction: true
  discrete_steps: 1000
  ligand_atom_feature_dim: 13
  net_config:
    act_fn: relu
    cutoff_mode: knn
    edge_feat_dim: 4
    ew_net_type: global
    hidden_dim: 128
    knn: 32
    n_heads: 16
    name: unio2net
    norm: true
    num_blocks: 1
    num_h2x: 1
    num_layers: 9
    num_node_types: 8
    num_r_gaussian: 20
    num_x2h: 1
    r_max: 10.0
    sync_twoup: false
    x2h_out_fc: false
  node_indicator: true
  pos_init_mode: zero
  protein_atom_feature_dim: 27
  sampling_strategy: end_back_pmf
  sigma1_coord: 0.03
  t_min: 0.0001
  time_emb_dim: 1
  time_emb_mode: simple
  use_discrete_t: true
empty_folder: false
evaluation:
  batch_size: 100
  ckpt_path: ./checkpoints/last.ckpt
  docking_config:
    exhaustiveness: 16
    mode: vina_score
    protein_root: ./
  ligand_path: 'null'
  num_samples: 10
  protein_path: 'null'
  sample_num_atoms: prior
  sample_steps: 100
exp_name: demo
logging_level: warning
no_wandb: false
project_name: kevin_bfn_sbdd
revision: default
seed: 1234
test_only: false
train:
  batch_size: 8
  ckpt_freq: 1
  ema_decay: 0.999
  epochs: 15
  max_grad_norm: Q
  num_workers: 8
  optimizer:
    beta1: 0.95
    beta2: 0.999
    lr: 0.0005
    type: adam
    weight_decay: 0
  pos_noise_std: 0
  random_rot: false
  resume: false
  scheduler:
    factor: 0.6
    max_iters: 20000
    min_lr: 1.0e-06
    patience: 10
    type: plateau
  v_loss_weight: 1
  val_freq: 2000
visual:
  save_mols: false
  visual_chain: false
  visual_nums: 10
wandb_resume_id: null
